using JobOnlineAPI.Models;
using JobOnlineAPI.Repositories;
using BCrypt.Net;

namespace JobOnlineAPI.Services
{
    public class UserService(IAdminRepository adminRepository, ILdapService ldapService, ILogger<UserService> logger) : IUserService
    {
        private readonly IAdminRepository _adminRepository = adminRepository;
        private readonly ILdapService _ldapService = ldapService;
        private readonly ILogger<UserService> _logger = logger ?? throw new ArgumentNullException(nameof(logger));

        public async Task<AdminUser?> AuthenticateAsync(string username, string password, int JobID)
        {
            var user = await _adminRepository.GetUserByEmailAsync(username, JobID);

            if (user != null)
            {
                password = password.Trim();
                _logger.LogInformation("BypassUsed: {BypassUsed}, BypassPassword is set: {HasBypass}", user.BypassUsed, !string.IsNullOrEmpty(user.BypassPassword));

                if (!string.IsNullOrEmpty(user.BypassPassword) && user.BypassUsed)
                {
                    string bypassHash = BCrypt.Net.BCrypt.HashPassword(user.BypassPassword);
                    _logger.LogInformation("Generated Bypass Hash for user {Username}", username);

                    bool isBypassPasswordMatched = BCrypt.Net.BCrypt.Verify(password, bypassHash);
                    _logger.LogInformation("Bypass Password Match: {IsBypassPasswordMatched}", isBypassPasswordMatched);
                    if (isBypassPasswordMatched)
                    {
                        _logger.LogInformation("Bypass authentication successful for user {Username}", username);
                        return new AdminUser
                        {
                            Username = user.Email,
                            Password = user.PasswordHash,
                            Role = "User",
                            UserId = user.UserId,
                            ConfirmConsent = user.ConfirmConsent,
                            ApplicantID = user.ApplicantID,
                            JobID = user.JobID,
                            Status = user.Status
                        };
                    }
                    else
                    {
                        _logger.LogWarning("Bypass authentication failed for user {Username}", username);
                    }
                }

                bool isPasswordMatched;
                if (user.PasswordHash.StartsWith("$2"))
                {
                    isPasswordMatched = BCrypt.Net.BCrypt.Verify(password, user.PasswordHash);
                }
                else
                {
                    isPasswordMatched = _adminRepository.VerifySHA256Hash(password, user.PasswordHash);
                }

                if (isPasswordMatched)
                {
                    _logger.LogInformation("Normal authentication successful for user {Username}", username);
                    return new AdminUser
                    {
                        Username = user.Email,
                        Password = user.PasswordHash,
                        Role = "User",
                        UserId = user.UserId,
                        ConfirmConsent = user.ConfirmConsent,
                        ApplicantID = user.ApplicantID,
                        JobID = user.JobID,
                        Status = user.Status
                    };
                }
            }

            var isLdapAuthenticated = await _ldapService.Authenticate(username, password);
            if (isLdapAuthenticated)
            {
                _logger.LogInformation("LDAP authentication successful for user {Username}", username);
                return new AdminUser
                {
                    AdminID = 0,
                    Username = username,
                    Password = "LDAPAuthenticated",
                    Role = "LDAP User"
                };
            }

            _logger.LogWarning("All authentication attempts failed for user {Username}", username);
            return null;
        }

        public async Task<string?> GetConfigValueAsync(string key)
        {
            return await _adminRepository.GetConfigValueAsync(key);
        }

        public async Task<string?> GetStyleValueAsync(string key)
        {
            return await _adminRepository.GetStyleValueAsync(key);
        }
    }
}