SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
ALTER FUNCTION [dbo].[fn_GetDepartmentNameFromCoscent]
(
    @Coscent NVARCHAR(255)
)
RETURNS TABLE
AS
RETURN
(
    SELECT TOP 1
        NAMECOSTCENT AS DEPARTMENTNAME
    FROM [HRMS_LINKED_SERVER].HRMS.dbo.T_EMPLOYEE_SSO
    WHERE COSTCENT = @Coscent
);
GO
